/*Generar el script que crea cada una de las tablas que conforman la base de
datos propuesta por el Comité Olímpico.*/

--CREACION DE TABLAS
CREATE TABLE PROFESION(
	cod_prof 	INTEGER 	NOT NULL,
	nombre 		VARCHAR(50) NOT NULL
);
CREATE TABLE PAIS(
	cod_pais 	INTEGER 	NOT NULL,
	nombre 		VARCHAR(50) NOT NULL
);
CREATE TABLE PUESTO(
	cod_puesto 	INTEGER 	NOT NULL,
	nombre 		VARCHAR(50) NOT NULL
);
CREATE TABLE DEPARTAMENTO(
	cod_depto 	INTEGER 	NOT NULL,
	nombre 		VARCHAR(50)
);
CREATE TABLE MIEMBRO(
	cod_miembro 		INTEGER 	NOT NULL,
	nombre 				VARCHAR(100)NOT NULL,
	apellido			VARCHAR(100)NOT NULL,
	edad 				INTEGER 	NOT NULL,
	telefono 			INTEGER				,
	residencia			VARCHAR(100)      	,
	PAIS_cod_pais		INTEGER 	NOT NULL,
	PROFESION_cod_prof	INTEGER 	NOT NULL
);
CREATE TABLE PUESTO_MIEMBRO(
	MIEMBRO_cod_miembro 	INTEGER 	NOT NULL,
	PUESTO_cod_puesto		INTEGER 	NOT NULL,
	DEPARTAMENTO_cod_depto	INTEGER 	NOT NULL,
	fecha_inicio			DATE 		NOT NULL,
	fecha_fin				DATE
);
CREATE TABLE TIPO_MEDALLA(
	cod_tipo	INTEGER		NOT NULL,
	medalla 	VARCHAR(20) NOT NULL
);
CREATE TABLE MEDALLERO(
	PAIS_cod_pais 			INTEGER 	NOT NULL,
	cantidad_medallas		INTEGER		NOT NULL,
	TIPO_MEDALLA_cod_tipo	INTEGER 	NOT NULL
);
CREATE TABLE DISCIPLINA(
	cod_disciplina	INTEGER 	NOT NULL,
	nombre			VARCHAR(50) NOT NULL,
	descripcion		VARCHAR(150)
);
CREATE TABLE ATLETA(
	cod_atleta					INTEGER		NOT NULL,
	nombre 						VARCHAR(50)	NOT NULL,
	apellido 					VARCHAR(50) NOT NULL,
	edad						INTEGER 	NOT NULL,
	Participaciones				VARCHAR(100)NOT NULL,
	DISCIPLINA_cod_disciplina	INTEGER		NOT NULL,
	PAIS_cod_pais 				INTEGER 	NOT NULL
);
CREATE TABLE CATEGORIA(
	cod_categoria 	INTEGER 	NOT NULL,
	categoria 		VARCHAR(50) NOT NULL
);
CREATE TABLE TIPO_PARTICIPACION(
	cod_participacion	INTEGER		NOT NULL,
	tipo_participacion 	VARCHAR(100)NOT NULL
);
CREATE TABLE EVENTO(
	cod_evento								INTEGER 	NOT NULL,
	fecha 									DATE 		NOT NULL,
	ubicacion								VARCHAR(50) NOT NULL,
	hora									DATE 		NOT NULL,
	DISCIPLINA_cod_disciplina				INTEGER 	NOT NULL,
	TIPO_PARTICIPACION_cod_participacion	INTEGER 	NOT NULL,
	CATEGORIA_cod_categoria					INTEGER		NOT NULL
);
CREATE TABLE EVENTO_ATLETA(
	ATLETA_cod_atleta	INTEGER NOT NULL,
	EVENTO_cod_evento	INTEGER NOT NULL
);
CREATE TABLE TELEVISORA(
	cod_televisora	INTEGER 	NOT NULL,
	nombre			VARCHAR(50) NOT NULL
);
CREATE TABLE COSTO_EVENTO(
	EVENTO_cod_evento 			INTEGER		NOT NULL,
	TELEVISORA_cod_televisora	INTEGER		NOT NULL,
	Tarifa						INTEGER 	NOT NULL
);

--CREACION DE CONSTRAINTS
ALTER TABLE PROFESION
	ADD CONSTRAINT PK_profesion
   	PRIMARY KEY(cod_prof);
ALTER TABLE PROFESION
   ADD CONSTRAINT UQ_profesion_nombre
   UNIQUE (nombre);

ALTER TABLE PAIS
	ADD CONSTRAINT PK_pais
   	PRIMARY KEY(cod_pais);
ALTER TABLE PAIS
   ADD CONSTRAINT UQ_pais_nombre
   UNIQUE (nombre);

ALTER TABLE PUESTO
	ADD CONSTRAINT PK_puesto
   	PRIMARY KEY(cod_puesto);
ALTER TABLE PUESTO
   ADD CONSTRAINT UQ_puesto_nombre
   UNIQUE (nombre);

ALTER TABLE DEPARTAMENTO
	ADD CONSTRAINT PK_departamento
   	PRIMARY KEY(cod_depto);
ALTER TABLE DEPARTAMENTO
   ADD CONSTRAINT UQ_departamento_nombre
   UNIQUE (nombre);

ALTER TABLE MIEMBRO
	ADD CONSTRAINT PK_miembro
   	PRIMARY KEY(cod_miembro);
ALTER TABLE MIEMBRO
   ADD CONSTRAINT FK_miembro_pais
   FOREIGN KEY (PAIS_cod_pais) REFERENCES PAIS(cod_pais) ON DELETE CASCADE;
ALTER TABLE MIEMBRO
   ADD CONSTRAINT FK_miembro_profesion
   FOREIGN KEY (PROFESION_cod_prof) REFERENCES PROFESION(cod_prof) ON DELETE CASCADE;

ALTER TABLE PUESTO_MIEMBRO
	ADD CONSTRAINT PK_puesto_miembro
	PRIMARY KEY (MIEMBRO_cod_miembro, PUESTO_cod_puesto, DEPARTAMENTO_cod_depto);
ALTER TABLE PUESTO_MIEMBRO
	ADD CONSTRAINT FK_puesto_miembro_miembro
	FOREIGN KEY (MIEMBRO_cod_miembro) REFERENCES MIEMBRO(cod_miembro) ON DELETE CASCADE;
ALTER TABLE PUESTO_MIEMBRO
	ADD CONSTRAINT FK_puesto_miembro_puesto
	FOREIGN KEY (PUESTO_cod_puesto) REFERENCES PUESTO(cod_puesto) ON DELETE CASCADE;
ALTER TABLE PUESTO_MIEMBRO
	ADD CONSTRAINT FK_puesto_miembro_departamento
	FOREIGN KEY (DEPARTAMENTO_cod_depto) REFERENCES DEPARTAMENTO(cod_depto) ON DELETE CASCADE;

ALTER TABLE TIPO_MEDALLA
	ADD CONSTRAINT PK_tipo_medalla
	PRIMARY KEY (cod_tipo);
ALTER TABLE TIPO_MEDALLA
	ADD CONSTRAINT UQ_tipo_medalla_medalla
	UNIQUE (medalla);

ALTER TABLE MEDALLERO
	ADD CONSTRAINT PK_medallero
	PRIMARY KEY (PAIS_cod_pais, TIPO_MEDALLA_cod_tipo);
ALTER TABLE MEDALLERO
	ADD CONSTRAINT FK_medallero_pais
	FOREIGN KEY (PAIS_cod_pais) REFERENCES PAIS(cod_pais) ON DELETE CASCADE;
ALTER TABLE MEDALLERO
	ADD CONSTRAINT FK_medallero_tipo_medalla
	FOREIGN KEY (TIPO_MEDALLA_cod_tipo) REFERENCES TIPO_MEDALLA(cod_tipo) ON DELETE CASCADE;

ALTER TABLE DISCIPLINA
	ADD CONSTRAINT PK_disciplina
	PRIMARY KEY (cod_disciplina);

ALTER TABLE ATLETA
	ADD CONSTRAINT PK_atleta
	PRIMARY KEY (cod_atleta);
ALTER TABLE ATLETA
	ADD CONSTRAINT FK_atleta_disciplina
	FOREIGN KEY (DISCIPLINA_cod_disciplina) REFERENCES DISCIPLINA(cod_disciplina) ON DELETE CASCADE;
ALTER TABLE ATLETA
	ADD CONSTRAINT FK_atleta_pais
	FOREIGN KEY (PAIS_cod_pais) REFERENCES PAIS(cod_pais) ON DELETE CASCADE;

ALTER TABLE CATEGORIA
	ADD CONSTRAINT PK_categoria
	PRIMARY KEY (cod_categoria);

ALTER TABLE TIPO_PARTICIPACION
	ADD CONSTRAINT PK_tipo_participacion
	PRIMARY KEY (cod_participacion);

ALTER TABLE EVENTO
	ADD CONSTRAINT PK_evento
	PRIMARY KEY (cod_evento);
ALTER TABLE EVENTO
	ADD CONSTRAINT FK_evento_disciplina
	FOREIGN KEY (DISCIPLINA_cod_disciplina) REFERENCES DISCIPLINA(cod_disciplina) ON DELETE CASCADE;
ALTER TABLE EVENTO
	ADD CONSTRAINT FK_evento_tipo_participacion
	FOREIGN KEY (TIPO_PARTICIPACION_cod_participacion) REFERENCES TIPO_PARTICIPACION(cod_participacion) ON DELETE CASCADE;
ALTER TABLE EVENTO
	ADD CONSTRAINT FK_evento_categoria
	FOREIGN KEY (CATEGORIA_cod_categoria) REFERENCES CATEGORIA(cod_categoria) ON DELETE CASCADE;

ALTER TABLE EVENTO_ATLETA
	ADD CONSTRAINT PK_evento_atleta
	PRIMARY KEY (ATLETA_cod_atleta, EVENTO_cod_evento);
ALTER TABLE EVENTO_ATLETA
	ADD CONSTRAINT FK_evento_atleta_atleta
	FOREIGN KEY (ATLETA_cod_atleta) REFERENCES ATLETA(cod_atleta) ON DELETE CASCADE;
ALTER TABLE EVENTO_ATLETA
	ADD CONSTRAINT FK_evento_atleta_evento
	FOREIGN KEY (EVENTO_cod_evento) REFERENCES EVENTO(cod_evento) ON DELETE CASCADE;

ALTER TABLE TELEVISORA
	ADD CONSTRAINT PK_televisora
	PRIMARY KEY (cod_televisora);

ALTER TABLE COSTO_EVENTO
	ADD CONSTRAINT PK_costo_evento
	PRIMARY KEY (EVENTO_cod_evento, TELEVISORA_cod_televisora);
ALTER TABLE COSTO_EVENTO
	ADD CONSTRAINT FK_costo_evento_evento
	FOREIGN KEY (EVENTO_cod_evento) REFERENCES EVENTO(cod_evento) ON DELETE CASCADE;
ALTER TABLE COSTO_EVENTO
	ADD CONSTRAINT FK_costo_evento_televisora
	FOREIGN KEY (TELEVISORA_cod_televisora) REFERENCES TELEVISORA(cod_televisora) ON DELETE CASCADE;

COMMIT;